### ISSUE TITLE
LICENSE is missing

### ISSUE THREAD

**Issue by sukso96100** [canonical/ubuntu-cooker#1]
Greetings. Thanks for sharing useful tool.
Seems like LICENSE is still missing. Since it's part of PsUWI, I guess it also should be MIT.
But Since they're repos are different. License also cloud be different.
Could you clarify which LICENSE does this project use?

**Comment by car-meows** [comment]
Thanks for asking, I forget to include the license. Currently I don't have permission to change the About but it is no longer closely related to PsUWI and it is licensed under GPLv3. 

I will update the information now. Thank you for the heads up!
